// Declarations of the generated GUI asset tables (src/gui/data/Gui*.cpp, generated by
// re/scripts/extract_gui_assets.py from the bitmaps the ORIGINAL decoded in the emulator).
#pragma once

#include <cstdint>

namespace sq8l::gui::data {

// Form background, 626x430: palette (0x00RRGGBB) + one uint16 palette index per pixel.
constexpr int kBackgroundWidth = 626;
constexpr int kBackgroundHeight = 430;
extern const int kBackgroundPaletteSize;
extern const uint32_t kBackgroundPalette[];
extern const uint16_t kBackgroundIndex[];

// TAniGIF strips: frames of frameWidth x frameHeight, palette + uint8 indices
// (frame-major, then row-major).
struct SpriteData {
    const char* name;
    int frameWidth, frameHeight, count;
    const uint32_t* palette;
    int paletteSize;
    const uint8_t* index;
};
constexpr int kSpriteCount = 8;
// Order: KnobGif, charGIF, numCharGIF, LedGIF, ButtGIF, smallButtGIF, upDownGif, scrButtGif.
extern const SpriteData kSprites[kSpriteCount];

}  // namespace sq8l::gui::data
