// Sprite strips (port of TAniGIF, unit AniGIF 0x456ebc-0x45733c) and the embedded assets.
#pragma once

#include <string>
#include <vector>

#include "Bitmap.h"

namespace sq8l::gui {

// TAniGIF: a GIF decoded into `count` frames of frameWidth x frameHeight
// (fields: +0x24 loaded, +0x30 frame width, +0x34 frame height, +0x38 frames, +0x3c count).
class Sprite {
public:
    Sprite() = default;
    Sprite(std::string name, int frameWidth, int frameHeight, int count, std::vector<Color> pixels);

    const std::string& name() const { return name_; }
    bool loaded() const { return count_ > 0; }
    int frameWidth() const { return fw_; }
    int frameHeight() const { return fh_; }
    int count() const { return count_; }

    // FUN_004572c4: the frame bitmap, or nil (null view) if not loaded or index >= count.
    // (The original does not check negative indices; callers never pass them.)
    ImageView frame(int index) const {
        if (!loaded() || index < 0 || index >= count_) return ImageView{};
        return ImageView{px_.data() + static_cast<size_t>(index) * fw_ * fh_, fw_, fh_, fw_};
    }

private:
    std::string name_;
    int fw_ = 0, fh_ = 0, count_ = 0;
    std::vector<Color> px_;
};

// The editor's bitmaps, exactly as the original decoded them (src/gui/data, generated by
// re/scripts/extract_gui_assets.py). Decoded on first use; thread-safe.
namespace assets {
const Bitmap& background();      // 626x430 form background (Form.Brush.Bitmap)
const Sprite& knobGif();         // KnobGif      128 frames 40x40
const Sprite& charGif();         // charGIF      272 frames 11x18 (68 chars x 4 attributes)
const Sprite& numCharGif();      // numCharGIF    17 frames 18x23 (red 7-segment)
const Sprite& ledGif();          // LedGIF         2 frames 14x14 (off, on)
const Sprite& buttGif();         // ButtGIF        6 frames 44x22 (grey, red, green; up/down each)
const Sprite& smallButtGif();    // smallButtGIF   2 frames 30x18
const Sprite& upDownGif();       // upDownGif      4 frames 30x18 (up, up pressed, down, down pressed)
const Sprite& scrButtGif();      // scrButtGif     4 frames 20x18 (up dim, up lit, down dim, down lit)
// By form component name ("KnobGif", "charGIF", ...); nullptr if unknown.
const Sprite* byName(const std::string& name);
}  // namespace assets

}  // namespace sq8l::gui
