// Generated by re/scripts/extract_gui_logic_data.py from the original SQ8L.dll (run in the
// emulator): the VFD page definitions of FUN_0047e340 with their setup, the character maps
// of the two TLCD3 displays and the formatter text tables. Do not edit.
#include "../LcdData.h"

namespace sq8l::gui::data {

static const ParamSetup kParams_0_0[] = {
    {2, "Enable oscillator 1", 12, Fmt::None, PopText::None, true, 0, Change::None},  // ENABLE1
    {3, "Enable oscillator 2", 31, Fmt::None, PopText::None, true, 0, Change::None},  // ENABLE2
    {4, "Enable oscillator 3", 50, Fmt::None, PopText::None, true, 0, Change::None},  // ENABLE3
    {5, "Amount of amplitude modulation by envelope 4 (=main volume)", 273, Fmt::None, PopText::None, true, 0, Change::None},  // ENV4.AMT
    {7, "Volume of oscillator 1", 11, Fmt::None, PopText::None, true, 0, Change::None},  // LEVEL1
    {8, "Volume of oscillator 2", 30, Fmt::None, PopText::None, true, 0, Change::None},  // LEVEL2
    {9, "Volume of oscillator 3", 49, Fmt::None, PopText::None, true, 0, Change::None},  // LEVEL3
    {10, "Saturation amount (EMU=close to original SQ80)", 279, Fmt::Saturation, PopText::None, false, 0, Change::None},  // SAT
};
static const ParamSetup kParams_0_1[] = {
    {2, "Waveform of oscillator 1", 3, Fmt::Wave, PopText::None, true, 25, Change::None},  // WAVE1
    {3, "Waveform of oscillator 2", 22, Fmt::Wave, PopText::None, true, 25, Change::None},  // WAVE2
    {4, "Waveform of oscillator 3", 41, Fmt::Wave, PopText::None, true, 25, Change::None},  // WAVE3
    {5, "Sync oscilllator 2 to oscillator 1", 324, Fmt::None, PopText::None, true, 0, Change::Form},  // SYNC
    {7, "Octave shift of oscillator 1", 0, Fmt::None, PopText::None, true, 0, Change::None},  // OCT1
    {8, "Octave shift of oscillator 2", 19, Fmt::None, PopText::None, true, 0, Change::None},  // OCT2
    {9, "Octave shift of oscillator 3", 38, Fmt::None, PopText::None, true, 0, Change::None},  // OCT3
    {10, "Amplitude of oscillator 2 is modulated by oscillator 1", 325, Fmt::None, PopText::None, true, 0, Change::Form},  // XMOD
};
static const ParamSetup kParams_0_2[] = {
    {2, "Semitone shift of oscillator 1", 1, Fmt::None, PopText::None, true, 0, Change::None},  // SEMI1
    {3, "Semitone shift of oscillator 2", 20, Fmt::None, PopText::None, true, 0, Change::None},  // SEMI2
    {4, "Semitone shift of oscillator 3", 39, Fmt::None, PopText::None, true, 0, Change::None},  // SEMI3
    {5, "Sync oscilllator 2 to oscillator 1", 324, Fmt::None, PopText::None, true, 0, Change::Form},  // SYNC
    {7, "Fine tune of oscillator 1", 2, Fmt::None, PopText::None, true, 0, Change::None},  // FINE1
    {8, "Fine tune of oscillator 2", 21, Fmt::None, PopText::None, true, 0, Change::None},  // FINE2
    {9, "Fine tune of oscillator 3", 40, Fmt::None, PopText::None, true, 0, Change::None},  // FINE3
    {10, "Amplitude of oscillator 2 is modulated by oscillator 1", 325, Fmt::None, PopText::None, true, 0, Change::Form},  // XMOD
};
static const ParamSetup kParams_1_0[] = {
    {1, "Octave shift of oscillator", -1, Fmt::None, PopText::None, true, 0, Change::None},  // OCT
    {2, "Semitone shift of oscillator", -1, Fmt::None, PopText::None, true, 0, Change::None},  // SEMI
    {3, "Fine tune of oscillator", -1, Fmt::None, PopText::None, true, 0, Change::None},  // FINE
    {4, "Waveform of oscillator", -1, Fmt::Wave, PopText::None, true, 25, Change::None},  // WAVE
    {7, "Pitch modulation source 1", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD1.SEL
    {9, "Pitch modulation amount 1", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD1.AMT
    {10, "Pitch modulation source 2", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD2.SEL
    {12, "Pitch modulation amount 2", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD2.AMT
};
static const ParamSetup kParams_1_1[] = {
    {1, "Volume of oscillator", -1, Fmt::None, PopText::None, true, 0, Change::None},  // LEVEL
    {2, "Enable oscillator", -1, Fmt::None, PopText::None, true, 0, Change::None},  // ENABLE
    {4, "Amplitude modulation source 1", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD1.SEL
    {6, "Amplitude modulation amount 1", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD1.AMT
    {7, "Amplitude modulation source 2", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD2.SEL
    {9, "Amplitude modulation amount 2", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD2.AMT
};
static const ParamSetup kParams_2_0[] = {
    {1, "Octave shift of oscillator", -1, Fmt::None, PopText::None, true, 0, Change::None},  // OCT
    {2, "Semitone shift of oscillator", -1, Fmt::None, PopText::None, true, 0, Change::None},  // SEMI
    {3, "Fine tune of oscillator", -1, Fmt::None, PopText::None, true, 0, Change::None},  // FINE
    {4, "Waveform of oscillator", -1, Fmt::Wave, PopText::None, true, 25, Change::None},  // WAVE
    {7, "Pitch modulation source 1", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD1.SEL
    {9, "Pitch modulation amount 1", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD1.AMT
    {10, "Pitch modulation source 2", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD2.SEL
    {12, "Pitch modulation amount 2", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD2.AMT
};
static const ParamSetup kParams_2_1[] = {
    {1, "Volume of oscillator", -1, Fmt::None, PopText::None, true, 0, Change::None},  // LEVEL
    {2, "Enable oscillator", -1, Fmt::None, PopText::None, true, 0, Change::None},  // ENABLE
    {4, "Amplitude modulation source 1", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD1.SEL
    {6, "Amplitude modulation amount 1", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD1.AMT
    {7, "Amplitude modulation source 2", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD2.SEL
    {9, "Amplitude modulation amount 2", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD2.AMT
};
static const ParamSetup kParams_3_0[] = {
    {1, "Octave shift of oscillator", -1, Fmt::None, PopText::None, true, 0, Change::None},  // OCT
    {2, "Semitone shift of oscillator", -1, Fmt::None, PopText::None, true, 0, Change::None},  // SEMI
    {3, "Fine tune of oscillator", -1, Fmt::None, PopText::None, true, 0, Change::None},  // FINE
    {4, "Waveform of oscillator", -1, Fmt::Wave, PopText::None, true, 25, Change::None},  // WAVE
    {7, "Pitch modulation source 1", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD1.SEL
    {9, "Pitch modulation amount 1", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD1.AMT
    {10, "Pitch modulation source 2", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD2.SEL
    {12, "Pitch modulation amount 2", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD2.AMT
};
static const ParamSetup kParams_3_1[] = {
    {1, "Volume of oscillator", -1, Fmt::None, PopText::None, true, 0, Change::None},  // LEVEL
    {2, "Enable oscillator", -1, Fmt::None, PopText::None, true, 0, Change::None},  // ENABLE
    {4, "Amplitude modulation source 1", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD1.SEL
    {6, "Amplitude modulation amount 1", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD1.AMT
    {7, "Amplitude modulation source 2", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD2.SEL
    {9, "Amplitude modulation amount 2", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD2.AMT
};
static const ParamSetup kParams_4_0[] = {
    {1, "Filter cutoff frequency", -1, Fmt::None, PopText::None, true, 0, Change::None},  // FREQ
    {2, "Filter resonance (Q)", -1, Fmt::None, PopText::None, true, 0, Change::None},  // RES
    {3, "Keyboard follow (frequency is modulated by key position)", -1, Fmt::None, PopText::None, true, 0, Change::None},  // KEYBD
    {5, "Frequency modulation source 1", 241, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD1.SEL
    {7, "Frequency modulation amount 1", 242, Fmt::None, PopText::None, true, 0, Change::None},  // MOD1.AMT
    {8, "Frequency modulation source 2", 243, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD2.SEL
    {10, "Frequency modulation amount 2", 244, Fmt::None, PopText::None, true, 0, Change::None},  // MOD2.AMT
};
static const ParamSetup kParams_5_0[] = {
    {1, "Amount of amplitude modulation by envelope 4 (=main volume)", -1, Fmt::None, PopText::None, true, 0, Change::None},  // ENV4.AMT
    {2, "Saturation amount (EMU=close to original SQ80)", 279, Fmt::Saturation, PopText::None, false, 0, Change::None},  // SAT
    {3, "Stereo panning", 274, Fmt::None, PopText::None, true, 0, Change::None},  // PAN
    {5, "Amplitude modulation source", 275, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // AMOD.SEL
    {7, "Amplitude modulation amount", 276, Fmt::None, PopText::None, true, 0, Change::None},  // AMOD.AMT
    {8, "Panning modulation source", 277, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // PMOD.SEL
    {10, "Panning modulation amount", 278, Fmt::None, PopText::None, true, 0, Change::None},  // PMOD.AMT
};
static const ParamSetup kParams_6_0[] = {
    {1, "LFO frequency", 133, Fmt::None, PopText::None, true, 0, Change::None},  // FREQ
    {2, "Reset LFO phase to specified value when voice is triggered", 134, Fmt::LfoReset, PopText::None, false, 0, Change::None},  // RESET
    {3, "LFO humanization (EMU=emulate SQ80, X1=humanize always, Xn=humanize n times as much)", 135, Fmt::LfoHuman, PopText::None, true, 0, Change::None},  // HUMAN
    {4, "LFO waveform", 136, Fmt::LfoWave, PopText::LfoWave, false, 0, Change::None},  // WAVE
    {5, "Start amplitude of LFO", 137, Fmt::None, PopText::None, true, 0, Change::None},  // L1
    {6, "Speed of LFO amplitude fading", 138, Fmt::None, PopText::None, true, 0, Change::None},  // DELAY
    {7, "Final amplitude of LFO", 141, Fmt::None, PopText::None, true, 0, Change::None},  // L2
    {9, "LFO amplitude modulation source", 142, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD.SEL
    {11, "LFO amplitude modulation amount", 143, Fmt::None, PopText::None, true, 0, Change::None},  // MOD.AMT
};
static const ParamSetup kParams_6_1[] = {
    {2, "LFO frequency modulation source", 144, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // FMOD.SEL
    {4, "LFO frequency modulation amount", 145, Fmt::None, PopText::None, true, 0, Change::None},  // FMOD.AMT
    {5, "LFO phase offset (\"T\" indicates Twin Mode = output difference of 2 phase-shifted waves)", 151, Fmt::LfoPhase, PopText::None, true, 0, Change::None},  // PHS
    {6, "Smoothness of LFO output (0=neutral)", 152, Fmt::None, PopText::None, true, 0, Change::None},  // SMTH
    {8, "LFO delay mode (EMU=like SQ80, SMTH=smoother fading)", 139, Fmt::LfoDelayMode, PopText::None, true, 0, Change::None},  // DLYM
    {9, "Main modulator: UNI=unipolar AM (like SQ80), BIP=bipolar AM, PHS=phase mod., SMT=smoothness mod.", 146, Fmt::LfoModMode, PopText::None, true, 0, Change::None},  // AMM
    {10, "Frequency modulator: UNI=unipolar FM, BIP=bipolar FM, PHS=phase mod., SMT=smoothness mod.", 147, Fmt::LfoModMode, PopText::None, true, 0, Change::None},  // FMM
    {11, "Play mode (FWD=forward, REV=backwards, 1XF=one-shot forw., 1XR=one-shot backw.)", 148, Fmt::LfoPlay, PopText::None, true, 0, Change::None},  // PLAY
};
static const ParamSetup kParams_7_0[] = {
    {1, "LFO frequency", 153, Fmt::None, PopText::None, true, 0, Change::None},  // FREQ
    {2, "Reset LFO phase to specified value when voice is triggered", 154, Fmt::LfoReset, PopText::None, false, 0, Change::None},  // RESET
    {3, "LFO humanization (EMU=emulate SQ80, X1=humanize always, Xn=humanize n times as much)", 155, Fmt::LfoHuman, PopText::None, true, 0, Change::None},  // HUMAN
    {4, "LFO waveform", 156, Fmt::LfoWave, PopText::LfoWave, false, 0, Change::None},  // WAVE
    {5, "Start amplitude of LFO", 157, Fmt::None, PopText::None, true, 0, Change::None},  // L1
    {6, "Speed of LFO amplitude fading", 158, Fmt::None, PopText::None, true, 0, Change::None},  // DELAY
    {7, "Final amplitude of LFO", 161, Fmt::None, PopText::None, true, 0, Change::None},  // L2
    {9, "LFO amplitude modulation source", 162, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD.SEL
    {11, "LFO amplitude modulation amount", 163, Fmt::None, PopText::None, true, 0, Change::None},  // MOD.AMT
};
static const ParamSetup kParams_7_1[] = {
    {2, "LFO frequency modulation source", 164, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // FMOD.SEL
    {4, "LFO frequency modulation amount", 165, Fmt::None, PopText::None, true, 0, Change::None},  // FMOD.AMT
    {5, "LFO phase offset (\"T\" indicates Twin Mode = output difference of 2 phase-shifted waves)", 171, Fmt::LfoPhase, PopText::None, true, 0, Change::None},  // PHS
    {6, "Smoothness of LFO output (0=neutral)", 172, Fmt::None, PopText::None, true, 0, Change::None},  // SMTH
    {8, "LFO delay mode (EMU=like SQ80, SMTH=smoother fading)", 159, Fmt::LfoDelayMode, PopText::None, true, 0, Change::None},  // DLYM
    {9, "Main modulator: UNI=unipolar AM (like SQ80), BIP=bipolar AM, PHS=phase mod., SMT=smoothness mod.", 166, Fmt::LfoModMode, PopText::None, true, 0, Change::None},  // AMM
    {10, "Frequency modulator: UNI=unipolar FM, BIP=bipolar FM, PHS=phase mod., SMT=smoothness mod.", 167, Fmt::LfoModMode, PopText::None, true, 0, Change::None},  // FMM
    {11, "Play mode (FWD=forward, REV=backwards, 1XF=one-shot forw., 1XR=one-shot backw.)", 168, Fmt::LfoPlay, PopText::None, true, 0, Change::None},  // PLAY
};
static const ParamSetup kParams_8_0[] = {
    {1, "LFO frequency", 173, Fmt::None, PopText::None, true, 0, Change::None},  // FREQ
    {2, "Reset LFO phase to specified value when voice is triggered", 174, Fmt::LfoReset, PopText::None, false, 0, Change::None},  // RESET
    {3, "LFO humanization (EMU=emulate SQ80, X1=humanize always, Xn=humanize n times as much)", 175, Fmt::LfoHuman, PopText::None, true, 0, Change::None},  // HUMAN
    {4, "LFO waveform", 176, Fmt::LfoWave, PopText::LfoWave, false, 0, Change::None},  // WAVE
    {5, "Start amplitude of LFO", 177, Fmt::None, PopText::None, true, 0, Change::None},  // L1
    {6, "Speed of LFO amplitude fading", 178, Fmt::None, PopText::None, true, 0, Change::None},  // DELAY
    {7, "Final amplitude of LFO", 181, Fmt::None, PopText::None, true, 0, Change::None},  // L2
    {9, "LFO amplitude modulation source", 182, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD.SEL
    {11, "LFO amplitude modulation amount", 183, Fmt::None, PopText::None, true, 0, Change::None},  // MOD.AMT
};
static const ParamSetup kParams_8_1[] = {
    {2, "LFO frequency modulation source", 184, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // FMOD.SEL
    {4, "LFO frequency modulation amount", 185, Fmt::None, PopText::None, true, 0, Change::None},  // FMOD.AMT
    {5, "LFO phase offset (\"T\" indicates Twin Mode = output difference of 2 phase-shifted waves)", 191, Fmt::LfoPhase, PopText::None, true, 0, Change::None},  // PHS
    {6, "Smoothness of LFO output (0=neutral)", 192, Fmt::None, PopText::None, true, 0, Change::None},  // SMTH
    {8, "LFO delay mode (EMU=like SQ80, SMTH=smoother fading)", 179, Fmt::LfoDelayMode, PopText::None, true, 0, Change::None},  // DLYM
    {9, "Main modulator: UNI=unipolar AM (like SQ80), BIP=bipolar AM, PHS=phase mod., SMT=smoothness mod.", 186, Fmt::LfoModMode, PopText::None, true, 0, Change::None},  // AMM
    {10, "Frequency modulator: UNI=unipolar FM, BIP=bipolar FM, PHS=phase mod., SMT=smoothness mod.", 187, Fmt::LfoModMode, PopText::None, true, 0, Change::None},  // FMM
    {11, "Play mode (FWD=forward, REV=backwards, 1XF=one-shot forw., 1XR=one-shot backw.)", 188, Fmt::LfoPlay, PopText::None, true, 0, Change::None},  // PLAY
};
static const ParamSetup kParams_9_0[] = {
    {1, "LFO frequency", 193, Fmt::None, PopText::None, true, 0, Change::None},  // FREQ
    {2, "Reset LFO phase to specified value when voice is triggered", 194, Fmt::LfoReset, PopText::None, false, 0, Change::None},  // RESET
    {3, "LFO humanization (EMU=emulate SQ80, X1=humanize always, Xn=humanize n times as much)", 195, Fmt::LfoHuman, PopText::None, true, 0, Change::None},  // HUMAN
    {4, "LFO waveform", 196, Fmt::LfoWave, PopText::LfoWave, false, 0, Change::None},  // WAVE
    {5, "Start amplitude of LFO", 197, Fmt::None, PopText::None, true, 0, Change::None},  // L1
    {6, "Speed of LFO amplitude fading", 198, Fmt::None, PopText::None, true, 0, Change::None},  // DELAY
    {7, "Final amplitude of LFO", 201, Fmt::None, PopText::None, true, 0, Change::None},  // L2
    {9, "LFO amplitude modulation source", 202, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD.SEL
    {11, "LFO amplitude modulation amount", 203, Fmt::None, PopText::None, true, 0, Change::None},  // MOD.AMT
};
static const ParamSetup kParams_9_1[] = {
    {2, "LFO frequency modulation source", 204, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // FMOD.SEL
    {4, "LFO frequency modulation amount", 205, Fmt::None, PopText::None, true, 0, Change::None},  // FMOD.AMT
    {5, "LFO phase offset (\"T\" indicates Twin Mode = output difference of 2 phase-shifted waves)", 211, Fmt::LfoPhase, PopText::None, true, 0, Change::None},  // PHS
    {6, "Smoothness of LFO output (0=neutral)", 212, Fmt::None, PopText::None, true, 0, Change::None},  // SMTH
    {8, "LFO delay mode (EMU=like SQ80, SMTH=smoother fading)", 199, Fmt::LfoDelayMode, PopText::None, true, 0, Change::None},  // DLYM
    {9, "Main modulator: UNI=unipolar AM (like SQ80), BIP=bipolar AM, PHS=phase mod., SMT=smoothness mod.", 206, Fmt::LfoModMode, PopText::None, true, 0, Change::None},  // AMM
    {10, "Frequency modulator: UNI=unipolar FM, BIP=bipolar FM, PHS=phase mod., SMT=smoothness mod.", 207, Fmt::LfoModMode, PopText::None, true, 0, Change::None},  // FMM
    {11, "Play mode (FWD=forward, REV=backwards, 1XF=one-shot forw., 1XR=one-shot backw.)", 208, Fmt::LfoPlay, PopText::None, true, 0, Change::None},  // PLAY
};
static const ParamSetup kParams_10_0[] = {
    {1, "1st level of envelope (attack)", 58, Fmt::None, PopText::None, true, 0, Change::None},  // L1
    {2, "2nd level of envelope (decay)", 59, Fmt::None, PopText::None, true, 0, Change::None},  // L2
    {3, "Final level of envelope (sustain)", 60, Fmt::None, PopText::None, true, 0, Change::None},  // L3
    {4, "Modulation of levels by velocity (L=linear, X=exponential)", 62, Fmt::EnvVelLevel, PopText::None, false, 0, Change::None},  // LV
    {5, "Modulation of attack time by velocity", 63, Fmt::None, PopText::None, true, 0, Change::None},  // T1V
    {6, "Attack time", 64, Fmt::None, PopText::None, true, 0, Change::None},  // T1
    {7, "Decay time", 65, Fmt::None, PopText::None, true, 0, Change::None},  // T2
    {8, "2nd decay time (time it takes to reach sustain level)", 66, Fmt::None, PopText::None, true, 0, Change::None},  // T3
    {9, "Release time (\"R\" indicates the use of 2nd release)", 67, Fmt::EnvT4, PopText::None, false, 0, Change::None},  // T4
    {10, "Scale envelope times by key position", 68, Fmt::None, PopText::None, true, 0, Change::None},  // TK
};
static const ParamSetup kParams_10_1[] = {
    {1, "Start level of envelope", 57, Fmt::None, PopText::None, true, 0, Change::None},  // L0
    {2, "Envelope plays full cycle without sustain stage", 69, Fmt::None, PopText::None, true, 0, Change::None},  // CYC
    {3, "Envelope shaping curve (OFF=no shaping)", 70, Fmt::EnvShape, PopText::None, true, 0, Change::None},  // SHP
    {4, "Smoothness of envelope output (0=neutral)", 75, Fmt::None, PopText::None, true, 0, Change::None},  // SMTH
    {6, "T1V mode (T1=T1V is amount of T1 modulation by velocity, SMT=modulate smoothness instead)", 71, Fmt::EnvT1VMode, PopText::None, true, 0, Change::None},  // T1VM
};
static const ParamSetup kParams_11_0[] = {
    {1, "1st level of envelope (attack)", 77, Fmt::None, PopText::None, true, 0, Change::None},  // L1
    {2, "2nd level of envelope (decay)", 78, Fmt::None, PopText::None, true, 0, Change::None},  // L2
    {3, "Final level of envelope (sustain)", 79, Fmt::None, PopText::None, true, 0, Change::None},  // L3
    {4, "Modulation of levels by velocity (L=linear, X=exponential)", 81, Fmt::EnvVelLevel, PopText::None, false, 0, Change::None},  // LV
    {5, "Modulation of attack time by velocity", 82, Fmt::None, PopText::None, true, 0, Change::None},  // T1V
    {6, "Attack time", 83, Fmt::None, PopText::None, true, 0, Change::None},  // T1
    {7, "Decay time", 84, Fmt::None, PopText::None, true, 0, Change::None},  // T2
    {8, "2nd decay time (time it takes to reach sustain level)", 85, Fmt::None, PopText::None, true, 0, Change::None},  // T3
    {9, "Release time (\"R\" indicates the use of 2nd release)", 86, Fmt::EnvT4, PopText::None, false, 0, Change::None},  // T4
    {10, "Scale envelope times by key position", 87, Fmt::None, PopText::None, true, 0, Change::None},  // TK
};
static const ParamSetup kParams_11_1[] = {
    {1, "Start level of envelope", 76, Fmt::None, PopText::None, true, 0, Change::None},  // L0
    {2, "Envelope plays full cycle without sustain stage", 88, Fmt::None, PopText::None, true, 0, Change::None},  // CYC
    {3, "Envelope shaping curve (OFF=no shaping)", 89, Fmt::EnvShape, PopText::None, true, 0, Change::None},  // SHP
    {4, "Smoothness of envelope output (0=neutral)", 94, Fmt::None, PopText::None, true, 0, Change::None},  // SMTH
    {6, "T1V mode (T1=T1V is amount of T1 modulation by velocity, SMT=modulate smoothness instead)", 90, Fmt::EnvT1VMode, PopText::None, true, 0, Change::None},  // T1VM
};
static const ParamSetup kParams_12_0[] = {
    {1, "1st level of envelope (attack)", 96, Fmt::None, PopText::None, true, 0, Change::None},  // L1
    {2, "2nd level of envelope (decay)", 97, Fmt::None, PopText::None, true, 0, Change::None},  // L2
    {3, "Final level of envelope (sustain)", 98, Fmt::None, PopText::None, true, 0, Change::None},  // L3
    {4, "Modulation of levels by velocity (L=linear, X=exponential)", 100, Fmt::EnvVelLevel, PopText::None, false, 0, Change::None},  // LV
    {5, "Modulation of attack time by velocity", 101, Fmt::None, PopText::None, true, 0, Change::None},  // T1V
    {6, "Attack time", 102, Fmt::None, PopText::None, true, 0, Change::None},  // T1
    {7, "Decay time", 103, Fmt::None, PopText::None, true, 0, Change::None},  // T2
    {8, "2nd decay time (time it takes to reach sustain level)", 104, Fmt::None, PopText::None, true, 0, Change::None},  // T3
    {9, "Release time (\"R\" indicates the use of 2nd release)", 105, Fmt::EnvT4, PopText::None, false, 0, Change::None},  // T4
    {10, "Scale envelope times by key position", 106, Fmt::None, PopText::None, true, 0, Change::None},  // TK
};
static const ParamSetup kParams_12_1[] = {
    {1, "Start level of envelope", 95, Fmt::None, PopText::None, true, 0, Change::None},  // L0
    {2, "Envelope plays full cycle without sustain stage", 107, Fmt::None, PopText::None, true, 0, Change::None},  // CYC
    {3, "Envelope shaping curve (OFF=no shaping)", 108, Fmt::EnvShape, PopText::None, true, 0, Change::None},  // SHP
    {4, "Smoothness of envelope output (0=neutral)", 113, Fmt::None, PopText::None, true, 0, Change::None},  // SMTH
    {6, "T1V mode (T1=T1V is amount of T1 modulation by velocity, SMT=modulate smoothness instead)", 109, Fmt::EnvT1VMode, PopText::None, true, 0, Change::None},  // T1VM
};
static const ParamSetup kParams_13_0[] = {
    {1, "1st level of envelope (attack)", 115, Fmt::None, PopText::None, true, 0, Change::None},  // L1
    {2, "2nd level of envelope (decay)", 116, Fmt::None, PopText::None, true, 0, Change::None},  // L2
    {3, "Final level of envelope (sustain)", 117, Fmt::None, PopText::None, true, 0, Change::None},  // L3
    {4, "Modulation of levels by velocity (L=linear, X=exponential)", 119, Fmt::EnvVelLevel, PopText::None, false, 0, Change::None},  // LV
    {5, "Modulation of attack time by velocity", 120, Fmt::None, PopText::None, true, 0, Change::None},  // T1V
    {6, "Attack time", 121, Fmt::None, PopText::None, true, 0, Change::None},  // T1
    {7, "Decay time", 122, Fmt::None, PopText::None, true, 0, Change::None},  // T2
    {8, "2nd decay time (time it takes to reach sustain level)", 123, Fmt::None, PopText::None, true, 0, Change::None},  // T3
    {9, "Release time (\"R\" indicates the use of 2nd release)", 124, Fmt::EnvT4, PopText::None, false, 0, Change::None},  // T4
    {10, "Scale envelope times by key position", 125, Fmt::None, PopText::None, true, 0, Change::None},  // TK
};
static const ParamSetup kParams_13_1[] = {
    {1, "Start level of envelope", 114, Fmt::None, PopText::None, true, 0, Change::None},  // L0
    {2, "Envelope plays full cycle without sustain stage", 126, Fmt::None, PopText::None, true, 0, Change::None},  // CYC
    {3, "Envelope shaping curve (OFF=no shaping)", 127, Fmt::EnvShape, PopText::None, true, 0, Change::None},  // SHP
    {4, "Smoothness of envelope output (0=neutral)", 132, Fmt::None, PopText::None, true, 0, Change::None},  // SMTH
    {6, "T1V mode (T1=T1V is amount of T1 modulation by velocity, SMT=modulate smoothness instead)", 128, Fmt::EnvT1VMode, PopText::None, true, 0, Change::None},  // T1VM
};
static const ParamSetup kParams_14_0[] = {
    {2, "Modulation source 1", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD1.SEL
    {4, "Modulation amount 1", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD1.AMT
    {6, "Modulation source 2", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD2.SEL
    {8, "Modulation amount 2", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD2.AMT
    {10, "Modulation source 3", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD3.SEL
    {12, "Modulation amount 3", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD3.AMT
    {14, "Amplitude modulation source", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD4.SEL
    {16, "Amplitude modulation amount", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD4.AMT
};
static const ParamSetup kParams_15_0[] = {
    {2, "Modulation source 1", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD1.SEL
    {4, "Modulation amount 1", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD1.AMT
    {6, "Modulation source 2", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD2.SEL
    {8, "Modulation amount 2", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD2.AMT
    {10, "Modulation source 3", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD3.SEL
    {12, "Modulation amount 3", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD3.AMT
    {14, "Amplitude modulation source", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD4.SEL
    {16, "Amplitude modulation amount", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD4.AMT
};
static const ParamSetup kParams_16_0[] = {
    {2, "Modulation source 1", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD1.SEL
    {4, "Modulation amount 1", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD1.AMT
    {6, "Modulation source 2", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD2.SEL
    {8, "Modulation amount 2", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD2.AMT
    {10, "Modulation source 3", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD3.SEL
    {12, "Modulation amount 3", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD3.AMT
    {14, "Amplitude modulation source", -1, Fmt::ModSource, PopText::ModSource, false, 0, Change::None},  // MOD4.SEL
    {16, "Amplitude modulation amount", -1, Fmt::None, PopText::None, true, 0, Change::None},  // MOD4.AMT
};
static const ParamSetup kParams_17_0[] = {
    {1, "Sync oscillator 2 to oscillator 1", -1, Fmt::None, PopText::None, true, 0, Change::Form},  // SYNC
    {2, "Amplitude of oscillator 2 is modulated by oscillator 1", -1, Fmt::None, PopText::None, true, 0, Change::Form},  // XMOD
    {3, "Monophonic playback", -1, Fmt::None, PopText::None, true, 0, Change::Form},  // MONO
    {4, "Glide (=portamento) time", -1, Fmt::None, PopText::None, true, 0, Change::None},  // GLIDE
    {6, "Restart voice (if the same key is restruck, the same voice is used)", -1, Fmt::None, PopText::None, true, 0, Change::None},  // REST.VC
    {7, "Restart envelopes (envelopes always start at zero level)", -1, Fmt::None, PopText::None, true, 0, Change::None},  // REST.ENV
    {8, "Restart oscillators when triggering voice", -1, Fmt::None, PopText::None, true, 0, Change::None},  // REST.OSC
    {9, "Envelopes play full cycle without sustain stage", -1, Fmt::None, PopText::None, true, 0, Change::None},  // CYC
};
static const ParamSetup kParams_17_1[] = {
    {1, "Pitchbend range in semitones", -1, Fmt::None, PopText::None, true, 0, Change::None},  // BRANGE
    {2, "Pitchbend mode (selects which voices are affected by bend)", -1, Fmt::BendMode, PopText::None, true, 0, Change::None},  // BMODE
    {3, "Voice stealing mode (HARD=stop voice, SOFT=fade out)", 366, Fmt::VoiceSteal, PopText::None, false, 0, Change::None},  // VSTEAL
    {4, "Emulation of a bug in the SQ80 when AM=ON", 358, Fmt::None, PopText::None, true, 0, Change::None},  // AMBUG
};
static const ParamSetup kParams_17_2[] = {
    {2, "DCA1-3 smoothing mode (EMU=like SQ80, FAST=less accurate but without latency)", 359, Fmt::Dca13Mode, PopText::None, true, 0, Change::None},  // DCA13
    {3, "Muffling (OFF=crisp sound, ON=slightly muffled sound like SQ80)", 281, Fmt::None, PopText::None, true, 0, Change::None},  // MUF
    {4, "DCA4 smoothing (EMU=soft attack like SQ80, HARD=hard attack)", 368, Fmt::Dca4Mode, PopText::None, true, 0, Change::None},  // DCA4
    {5, "DC offset blocking filter for oscillator outputs (SMART=on when needed, ON=always on, OFF=off)", 360, Fmt::DcBlock, PopText::None, true, 0, Change::None},  // DCB
};

const PageSetup kPages[kNumPages] = {
    {"[OSC1-3] [OUTPUT=] [{1,ENABLE1,3,0,1}] 4 [{2,ENABLE2,3,0,1}] 4 [{3,ENABLE3,3,0,1}] 1 [FINAL={4,ENV4.AMT,2,0,63}]\\&7 [LEVEL=] 2 [{6,LEVEL1,2,0,63}] 5 [{7,LEVEL2,2,0,63}] 5 [{8,LEVEL3,2,0,63}] 2 [SAT={9,SAT,3,-1,15}]\\&[OSC1-3] [WAVE=] [{1,WAVE1,6,0,74}] 1 [{2,WAVE2,6,0,74}] 1 [{3,WAVE3,6,0,74}] [SYNC={4,SYNC,3,0,1}]\\&7 [OCT=] 3 [{6,OCT1,2,-3,+5}] 5 [{7,OCT2,2,-3,+5}] 5 [{8,OCT3,2,-3,+5}] 2 [AM={9,XMOD,3,0,1}]\\&[OSC1-3] [SEMI=] 2 [{1,SEMI1,3,-12,12}] 4 [{2,SEMI2,3,-12,12}] 4 [{3,SEMI3,3,-12,12}] 1 [SYNC={4,SYNC,3,0,1}]\\&7 [FINE=] 2 [{6,FINE1,3,-31,+31}] 4 [{7,FINE2,3,-31,+31}] 4 [{8,FINE3,3,-31,+31}] 1 [AM={9,XMOD,3,0,1}]",
     3, {
        {"OSC1-3 Mix", 0, 0, -1, 0, 0, 0, kParams_0_0, 8},
        {"Waves", 0, 0, -1, 0, 1, 0, kParams_0_1, 8},
        {"Tune", 0, 0, -1, 0, 1, 0, kParams_0_2, 8},
     }},
    {"[OSC1][OCT={0,OCT,2,-3,+5}] [SEMI={1,SEMI,3,-12,12}] [FINE={2,FINE,3,-31,+31}] 3 [WAVE={4,WAVE,6,0,74}] []\\&5 [MODS=] 3 [{6,MOD1.SEL,6,-1,145}] [*] [{7,MOD1.AMT,3,-63,+63}] 3 [{8,MOD2.SEL,6,-1,145}] [*] [{9,MOD2.AMT,3,-63,+63}]\\&[DCA1][LEVEL={0,LEVEL,2,0,63}] 3 [OUTPUT={2,ENABLE,3,0,1}]\\&5 [MODS=] 3 [{6,MOD1.SEL,6,-1,145}] [*] [{7,MOD1.AMT,3,-63,+63}] 3 [{8,MOD2.SEL,6,-1,145}] [*] [{9,MOD2.AMT,3,-63,+63}]",
     2, {
        {"OSC1", 1, 2, 0, 0, 0, 0, kParams_1_0, 8},
        {"DCA1", 1, 2, 11, 0, 1, 0, kParams_1_1, 6},
     }},
    {"[OSC2][OCT={0,OCT,2,-3,+5}] [SEMI={1,SEMI,3,-12,12}] [FINE={2,FINE,3,-31,+31}] 3 [WAVE={4,WAVE,6,0,74}] []\\&5 [MODS=] 3 [{6,MOD1.SEL,6,-1,145}] [*] [{7,MOD1.AMT,3,-63,+63}] 3 [{8,MOD2.SEL,6,-1,145}] [*] [{9,MOD2.AMT,3,-63,+63}]\\&[DCA2][LEVEL={0,LEVEL,2,0,63}] 3 [OUTPUT={2,ENABLE,3,0,1}]\\&5 [MODS=] 3 [{6,MOD1.SEL,6,-1,145}] [*] [{7,MOD1.AMT,3,-63,+63}] 3 [{8,MOD2.SEL,6,-1,145}] [*] [{9,MOD2.AMT,3,-63,+63}]",
     2, {
        {"OSC2", 2, 2, 19, 0, 0, 0, kParams_2_0, 8},
        {"DCA2", 2, 2, 30, 0, 1, 0, kParams_2_1, 6},
     }},
    {"[OSC3][OCT={0,OCT,2,-3,+5}] [SEMI={1,SEMI,3,-12,12}] [FINE={2,FINE,3,-31,+31}] 3 [WAVE={4,WAVE,6,0,74}] []\\&5 [MODS=] 3 [{6,MOD1.SEL,6,-1,145}] [*] [{7,MOD1.AMT,3,-63,+63}] 3 [{8,MOD2.SEL,6,-1,145}] [*] [{9,MOD2.AMT,3,-63,+63}]\\&[DCA3][LEVEL={0,LEVEL,2,0,63}] 3 [OUTPUT={2,ENABLE,3,0,1}]\\&5 [MODS=] 3 [{6,MOD1.SEL,6,-1,145}] [*] [{7,MOD1.AMT,3,-63,+63}] 3 [{8,MOD2.SEL,6,-1,145}] [*] [{9,MOD2.AMT,3,-63,+63}]",
     2, {
        {"OSC3", 3, 2, 38, 0, 0, 0, kParams_3_0, 8},
        {"DCA3", 3, 2, 49, 0, 1, 0, kParams_3_1, 6},
     }},
    {"[FILT][FREQ={0,FREQ,3,0,127}] [RES(Q)={1,RES,2,0,31}] 2 [KEYBD * {3,KEYBD,3,-63,+63}]\\&5 [MODS=] 2 [{6,MOD1.SEL,6,-1,145}] [*] [{7,MOD1.AMT,4,-127,+127}] 2 [{8,MOD2.SEL,6,-1,145}] [*] [{9,MOD2.AMT,4,-127,+127}]",
     1, {
        {"Filter", 4, 4, 237, 0, 0, 0, kParams_4_0, 7},
     }},
    {"[DCA4] [ENV4 * {0,ENV4.AMT,2,0,63}] 5 [SAT={2,SAT,3,-1,15}] 2 [PAN={3,PAN,3,-63,+63}]\\&5 [MODS=] 3 [{6,AMOD.SEL,6,-1,145}] [*] [{7,AMOD.AMT,3,-63,+63}] 3 [{8,PMOD.SEL,6,-1,145}] [*] [{9,PMOD.AMT,4,-127,+127}]",
     1, {
        {"Final Volume (DCA4)", 5, 6, 273, 0, 0, 0, kParams_5_0, 7},
     }},
    {"[LFO1][FREQ={0,FREQ,3,0,127}] [RESET={1,RESET,3,-1,63}] 1 [HUMAN={3,HUMAN,3,0,6}] 1 [WAV={4,WAVE,4,0,82}]\\&5 [L1={5,L1,2,0,63}] [DELAY={6,DELAY,2,0,63}] [L2={7,L2,2,0,63}] 1 [MOD=] [{8,MOD.SEL,6,-1,145}] [*] [{9,MOD.AMT,3,-63,+63}]\\&[LFO1][FREQMOD=] [{1,FMOD.SEL,6,-1,145}] [*] [{2,FMOD.AMT,4,-127,+127}] 1 [PHS={3,PHS,3,0,127}] [SMTH={4,SMTH,2,0,63}]\\&5 [MODE-] [DELAY={6,DLYM,4,0,1}] [AM={7,AMM,3,0,3}] [FM={8,FMM,3,0,3}] [PLAY={9,PLAY,3,0,3}]",
     2, {
        {"LFO1", 6, 7, 133, 0, 0, 0, kParams_6_0, 9},
        {"LFO1", 6, 7, 133, 0, 0, 1, kParams_6_1, 8},
     }},
    {"[LFO2][FREQ={0,FREQ,3,0,127}] [RESET={1,RESET,3,-1,63}] 1 [HUMAN={3,HUMAN,3,0,6}] 1 [WAV={4,WAVE,4,0,82}]\\&5 [L1={5,L1,2,0,63}] [DELAY={6,DELAY,2,0,63}] [L2={7,L2,2,0,63}] 1 [MOD=] [{8,MOD.SEL,6,-1,145}] [*] [{9,MOD.AMT,3,-63,+63}]\\&[LFO2][FREQMOD=] [{1,FMOD.SEL,6,-1,145}] [*] [{2,FMOD.AMT,4,-127,+127}] 1 [PHS={3,PHS,3,0,127}] [SMTH={4,SMTH,2,0,63}]\\&5 [MODE-] [DELAY={6,DLYM,4,0,1}] [AM={7,AMM,3,0,3}] [FM={8,FMM,3,0,3}] [PLAY={9,PLAY,3,0,3}]",
     2, {
        {"LFO2", 7, 7, 153, 0, 0, 0, kParams_7_0, 9},
        {"LFO2", 7, 7, 153, 0, 0, 1, kParams_7_1, 8},
     }},
    {"[LFO3][FREQ={0,FREQ,3,0,127}] [RESET={1,RESET,3,-1,63}] 1 [HUMAN={3,HUMAN,3,0,6}] 1 [WAV={4,WAVE,4,0,82}]\\&5 [L1={5,L1,2,0,63}] [DELAY={6,DELAY,2,0,63}] [L2={7,L2,2,0,63}] 1 [MOD=] [{8,MOD.SEL,6,-1,145}] [*] [{9,MOD.AMT,3,-63,+63}]\\&[LFO3][FREQMOD=] [{1,FMOD.SEL,6,-1,145}] [*] [{2,FMOD.AMT,4,-127,+127}] 1 [PHS={3,PHS,3,0,127}] [SMTH={4,SMTH,2,0,63}]\\&5 [MODE-] [DELAY={6,DLYM,4,0,1}] [AM={7,AMM,3,0,3}] [FM={8,FMM,3,0,3}] [PLAY={9,PLAY,3,0,3}]",
     2, {
        {"LFO3", 8, 7, 173, 0, 0, 0, kParams_8_0, 9},
        {"LFO3", 8, 7, 173, 0, 0, 1, kParams_8_1, 8},
     }},
    {"[LFO4][FREQ={0,FREQ,3,0,127}] [RESET={1,RESET,3,-1,63}] 1 [HUMAN={3,HUMAN,3,0,6}] 1 [WAV={4,WAVE,4,0,82}]\\&5 [L1={5,L1,2,0,63}] [DELAY={6,DELAY,2,0,63}] [L2={7,L2,2,0,63}] 1 [MOD=] [{8,MOD.SEL,6,-1,145}] [*] [{9,MOD.AMT,3,-63,+63}]\\&[LFO4][FREQMOD=] [{1,FMOD.SEL,6,-1,145}] [*] [{2,FMOD.AMT,4,-127,+127}] 1 [PHS={3,PHS,3,0,127}] [SMTH={4,SMTH,2,0,63}]\\&5 [MODE-] [DELAY={6,DLYM,4,0,1}] [AM={7,AMM,3,0,3}] [FM={8,FMM,3,0,3}] [PLAY={9,PLAY,3,0,3}]",
     2, {
        {"LFO4", 9, 7, 193, 0, 0, 0, kParams_9_0, 9},
        {"LFO4", 9, 7, 193, 0, 0, 1, kParams_9_1, 8},
     }},
    {"[ENV1][L1={0,L1,3,-63,+63}] 1 [L2={1,L2,3,-63,+63}] 1 [L3={2,L3,3,-63,+63}] 1 [LV={3,LV,3,0,127}] 2 [T1V={4,T1V,2,0,63}]\\&5 [T1={5,T1,2,0,63}] 2 [T2={6,T2,2,0,63}] 2 [T3={7,T3,2,0,63}] 2 [T4={8,T4,3,0,127}] 2 [TK={9,TK,2,0,63}]\\&[ENV1][L0={0,L0,3,-63,+63}] 1 [CYC={1,CYC,3,0,1}] 5 [SHAPE={3,SHP,4,0,7}] [SMTH={4,SMTH,2,0,63}]\\&5 [MODE-] 2 [T1V={6,T1VM,3,0,1}]",
     2, {
        {"ENV1", 10, 8, 57, 0, 0, 0, kParams_10_0, 10},
        {"ENV1", 10, 8, 57, 0, 0, 1, kParams_10_1, 5},
     }},
    {"[ENV2][L1={0,L1,3,-63,+63}] 1 [L2={1,L2,3,-63,+63}] 1 [L3={2,L3,3,-63,+63}] 1 [LV={3,LV,3,0,127}] 2 [T1V={4,T1V,2,0,63}]\\&5 [T1={5,T1,2,0,63}] 2 [T2={6,T2,2,0,63}] 2 [T3={7,T3,2,0,63}] 2 [T4={8,T4,3,0,127}] 2 [TK={9,TK,2,0,63}]\\&[ENV2][L0={0,L0,3,-63,+63}] 1 [CYC={1,CYC,3,0,1}] 5 [SHAPE={3,SHP,4,0,7}] [SMTH={4,SMTH,2,0,63}]\\&5 [MODE-] 2 [T1V={6,T1VM,3,0,1}]",
     2, {
        {"ENV2", 11, 8, 76, 0, 0, 0, kParams_11_0, 10},
        {"ENV2", 11, 8, 76, 0, 0, 1, kParams_11_1, 5},
     }},
    {"[ENV3][L1={0,L1,3,-63,+63}] 1 [L2={1,L2,3,-63,+63}] 1 [L3={2,L3,3,-63,+63}] 1 [LV={3,LV,3,0,127}] 2 [T1V={4,T1V,2,0,63}]\\&5 [T1={5,T1,2,0,63}] 2 [T2={6,T2,2,0,63}] 2 [T3={7,T3,2,0,63}] 2 [T4={8,T4,3,0,127}] 2 [TK={9,TK,2,0,63}]\\&[ENV3][L0={0,L0,3,-63,+63}] 1 [CYC={1,CYC,3,0,1}] 5 [SHAPE={3,SHP,4,0,7}] [SMTH={4,SMTH,2,0,63}]\\&5 [MODE-] 2 [T1V={6,T1VM,3,0,1}]",
     2, {
        {"ENV3", 12, 8, 95, 0, 0, 0, kParams_12_0, 10},
        {"ENV3", 12, 8, 95, 0, 0, 1, kParams_12_1, 5},
     }},
    {"[ENV4][L1={0,L1,3,-63,+63}] 1 [L2={1,L2,3,-63,+63}] 1 [L3={2,L3,3,-63,+63}] 1 [LV={3,LV,3,0,127}] 2 [T1V={4,T1V,2,0,63}]\\&5 [T1={5,T1,2,0,63}] 2 [T2={6,T2,2,0,63}] 2 [T3={7,T3,2,0,63}] 2 [T4={8,T4,3,0,127}] 2 [TK={9,TK,2,0,63}]\\&[ENV4][L0={0,L0,3,-63,+63}] 1 [CYC={1,CYC,3,0,1}] 5 [SHAPE={3,SHP,4,0,7}] [SMTH={4,SMTH,2,0,63}]\\&5 [MODE-] 2 [T1V={6,T1VM,3,0,1}]",
     2, {
        {"ENV4", 13, 8, 114, 0, 0, 0, kParams_13_0, 10},
        {"ENV4", 13, 8, 114, 0, 0, 1, kParams_13_1, 5},
     }},
    {"[MAT1]5 [M1=] [{1,MOD1.SEL,6,-1,145}] [*] [{2,MOD1.AMT,3,-63,+63}] 1 [M2=] [{3,MOD2.SEL,6,-1,145}] [*] [{4,MOD2.AMT,3,-63,+63}]\\&10 [M3=] [{6,MOD3.SEL,6,-1,145}] [*] [{7,MOD3.AMT,3,-63,+63}] [AMP=] [{8,MOD4.SEL,6,-1,145}] [*] [{9,MOD4.AMT,3,-63,+63}]",
     1, {
        {"Matrix1", 14, 9, 213, 0, 0, 0, kParams_14_0, 8},
     }},
    {"[MAT2]5 [M1=] [{1,MOD1.SEL,6,-1,145}] [*] [{2,MOD1.AMT,3,-63,+63}] 1 [M2=] [{3,MOD2.SEL,6,-1,145}] [*] [{4,MOD2.AMT,3,-63,+63}]\\&10 [M3=] [{6,MOD3.SEL,6,-1,145}] [*] [{7,MOD3.AMT,3,-63,+63}] [AMP=] [{8,MOD4.SEL,6,-1,145}] [*] [{9,MOD4.AMT,3,-63,+63}]",
     1, {
        {"Matrix2", 15, 9, 221, 0, 0, 0, kParams_15_0, 8},
     }},
    {"[MAT3]5 [M1=] [{1,MOD1.SEL,6,-1,145}] [*] [{2,MOD1.AMT,3,-63,+63}] 1 [M2=] [{3,MOD2.SEL,6,-1,145}] [*] [{4,MOD2.AMT,3,-63,+63}]\\&10 [M3=] [{6,MOD3.SEL,6,-1,145}] [*] [{7,MOD3.AMT,3,-63,+63}] [AMP=] [{8,MOD4.SEL,6,-1,145}] [*] [{9,MOD4.AMT,3,-63,+63}]",
     1, {
        {"Matrix3", 16, 9, 229, 0, 0, 0, kParams_16_0, 8},
     }},
    {"[MODE] [SYNC={0,SYNC,3,0,1}] [AM={1,XMOD,3,0,1}] 5 [MONO={3,MONO,3,0,1}] [GLIDE={4,GLIDE,2,0,63}]\\&5 [RESTART-] [VC={6,REST.VC,3,0,1}] [ENV={7,REST.ENV,3,0,1}] [OSC={8,REST.OSC,3,0,1}] [CYC={9,CYC,3,0,1}]\\&[EMU] 1 [BEND={0,BRANGE,2,0,36}] [MODE={1,BMODE,5,0,6}] 9 [VSTEAL={4,VSTEAL,4,-1,0}]\\&5 [AMBUG={5,AMBUG,3,0,1}]\\&[EMU] [SMOOTH-] [DCA1-3={1,DCA13,4,0,1}] 3 [MUFFLE={3,MUF,3,0,1}]\\&12 [DCA4={6,DCA4,4,0,1}] 4 [DC-BLOCK={8,DCB,3,0,2}]",
     3, {
        {"Modes", 17, 10, 324, 0, 0, 0, kParams_17_0, 8},
        {"Emulation", 17, 10, 356, 0, 0, 0, kParams_17_1, 4},
        {"Emulation", 17, 10, 356, 0, 0, 1, kParams_17_2, 4},
     }},
};

// oscillator waves (FUN_00461114)
const char* const kWaveNames[75] = {
    "   SAW", "  BELL", "  SINE", "SQUARE", " PULSE", "NOISE1", "NOISE2", "NOISE3",
    "  BASS", " PIANO", "EL PNO", "VOICE1", "VOICE2", "  KICK", "  REED", " ORGAN",
    "SYNTH1", "SYNTH2", "SYNTH3", "FORMT1", "FORMT2", "FORMT3", "FORMT4", "FORMT5",
    "PULSE2", "SQR  2", "4 OCTS", " PRIME", "BASS 2", "E PNO2", "OCTAVE", " OCT+5",
    "SAW  2", "TRIANG", "REED 2", "REED 3", "GRIT 1", "GRIT 2", "GRIT 3", "GLINT1",
    "GLINT2", "GLINT3", "  CLAV", " BRASS", "STRING", "DIGIT1", "DIGIT2", "BELL 2",
    " ALIEN", "BREATH", "VOICE3", " STEAM", " METAL", " CHIME", "BOWING", "PICK 1",
    "PICK 2", "MALLET", "  SLAP", " PLINK", " PLUCK", " PLUNK", " CLICK", " CHIFF",
    " THUMP", "LOGDRM", "KICK 2", " SNARE", "TOMTOM", "HI-HAT", "DRUMS1", "DRUMS2",
    "DRUMS3", "DRUMS4", "DRUMS5",
};
// modulation sources -1..145 (FUN_00461184)
const char* const kModSourceNames[147] = {
    " *OFF*", "  LFO1", "  LFO2", "  LFO3", "  LFO4", "  ENV1", "  ENV2", "  ENV3",
    "  ENV4", "   VEL", " VEL-X", "  KEYB", " KEYB2", " PRESS", "  MAT1", "  MAT2",
    "  MAT3", "  BANK", " WHEEL", "BREATH", " CTR 3", " PEDAL", " PORTA", "  DATA",
    "VOLUME", "BALANC", " CTR 9", "   PAN", "EXPRES", "EFFCT1", "EFFCT2", "CTR 14",
    "CTR 15", "GENP 1", "GENP 2", "GENP 3", "GENP 4", "CTR 20", "CTR 21", "CTR 22",
    "CTR 23", "CTR 24", "CTR 25", "CTR 26", "CTR 27", "CTR 28", "CTR 29", "CTR 30",
    "CTR 31", "BANKLO", "WHEELL", "BRTHLO", "CTR 35", "PEDALL", "PORTAL", "DATALO",
    "VOL LO", "BANKLO", "CTR 41", "PAN LO", "EXPRLO", "EFF1LO", "EFF2LO", "CTR 46",
    "CTR 47", "CTR 48", "CTR 49", "CTR 50", "CTR 51", "CTR 52", "CTR 53", "CTR 54",
    "CTR 55", "CTR 56", "CTR 57", "CTR 58", "CTR 59", "CTR 60", "CTR 61", "CTR 62",
    "CTR 63", "HLDPED", "PORTON", "SUSPED", "SFTPED", "LEGPED", "HLD2PD", "VARIAT",
    "TIMBRE", "RELEAS", "ATTACK", "BRIGHT", " SND 6", " SND 7", " SND 8", " SND 9",
    "SND 10", "GENP1H", "GENP2H", "GENP3H", "GENP4H", "CTR 84", "CTR 85", "CTR 86",
    "CTR 87", "CTR 88", "CTR 89", "CTR 90", "EFFLEV", "TREMOL", "CHORUS", "CELEST",
    "PHASER", "DATINC", "DATDEC", "NREGLO", "NREGHI", " REGLO", " REGHI", "CTR102",
    "CTR103", "CTR104", "CTR105", "CTR106", "CTR107", "CTR108", "CTR109", "CTR110",
    "CTR111", "CTR112", "CTR113", "CTR114", "CTR115", "CTR116", "CTR117", "CTR118",
    "CTR119", "SNDOFF", "CTROFF", " LOCAL", "ALLOFF", "OMNOFF", "OMNION", "  MONO",
    "  POLY", "CHPRES", "  BEND",
};
// LFO basic waves (FUN_004612e4)
const char* const kLfoWaveNames[5] = {
    "TRI", "SAW", "SQR", "NOI", "BIP",
};
// EXP/TAN shapes (FUN_00461928, LFO waves 75..82)
const char* const kShapeNames[8] = {
    "EXP ", "EXP2", "EXP3", "EXP4", "TAN ", "TAN2", "TAN3", "TAN4",
};
// pitch bend modes (FUN_004619d4)
const char* const kBendModeNames[7] = {
    "ALL", "HELD", "NEW", "NEWH", "HELD2", "NEW2", "NEWH2",
};
// LFO waves 5..74 -> oscillator wave (FUN_004613dc)
const uint8_t kLfoWaveMap[70] = {
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
    14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
    28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
    42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
    56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69,
};

const char kLcdChars[] = " \"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`{|}~";
const char kNumLcdChars[] = " 0123456789ABCDPU";

}  // namespace sq8l::gui::data
