"""Extract the LFO tables of the original (typed constants in the DATA section) and
generate src/engine/data/LfoData.cpp.

All tables are pure data: they are stored initialized in SQ8L.dll and never written
(the only code references are the reads in unit mod_lfo4_22, plus the envelope SHAPE
code reading the shaping tables). The script reads them from the emulator after the
plugin is loaded and checks that they equal the file contents.
"""
import os
import sys

import pefile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "oracle"))
sys.path.insert(0, os.path.join(ROOT, "tests"))
from harness import started_host  # noqa: E402

OUT = os.path.join(ROOT, "src", "engine", "data", "LfoData.cpp")

# (C name, address, size, signed, description)
TABLES = [
    ("kLfoWaveParams", 0x494C34, 70 * 4, False,
     "unit lfoWavParams (via pointer 0x4c30e8): per LFO wave 5..74 {osc wave, key offset, "
     "frequency shift, unused}"),
    ("kLfoShapeTables", 0x4C1688, 8 * 256, True,
     "unit lfoWavXtab (via pointer 0x4c3150): LFO waves 75..82 = EXP, EXP2..4, TAN, TAN2..4, "
     "256 signed samples each (also used by the envelope SHAPE)"),
    ("kLfoLevelShift", 0x4C1E88, 2, False,
     "mod_lfo4_22 0x4c1e88: level scale shift per delay mode (EMU, SMTH)"),
    ("kLfoAmShift", 0x4C1E8C, 2, False,
     "mod_lfo4_22 0x4c1e8c: AM amount scale shift per delay mode (EMU, SMTH)"),
    ("kLfoNoise", 0x4C1E90, 256, True,
     "mod_lfo4_22 0x4c1f10 (array[-128..127]): NOISE waveform, indexed by signed phase byte + 128"),
    ("kLfoHumanize", 0x4C1F90, 256, True,
     "mod_lfo4_22 0x4c2010 (array[-128..127]): humanization random steps {-1, 0, +1}, "
     "indexed by signed (counter & 0xff) + 128"),
]


def c_array(name, data, signed, per_line=24):
    ctype = "int8_t" if signed else "uint8_t"
    vals = [b - 256 if signed and b >= 128 else b for b in data]
    lines = [f"extern const {ctype} {name}[{len(data)}];", f"alignas(16) const {ctype} {name}[{len(data)}] = {{"]
    for i in range(0, len(vals), per_line):
        lines.append("    " + ",".join(str(v) for v in vals[i:i + per_line]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    pe = pefile.PE(os.path.join(ROOT, "original", "SQ8L.dll"))
    base = pe.OPTIONAL_HEADER.ImageBase
    h = started_host()
    e = h.emu
    assert e.u32(0x4C30E8) == 0x494C34 and e.u32(0x4C3150) == 0x4C1688
    parts = []
    for name, addr, size, signed, what in TABLES:
        mem = e.read(addr, size)
        assert mem == pe.get_data(addr - base, size), f"{name} differs from the file image"
        parts.append(f"// {what}\n" + c_array(name, mem, signed))
        print(f"{name}: {size} bytes @ {addr:#x}")
    with open(OUT, "w") as f:
        f.write("// Generated by re/scripts/extract_lfo_data.py from the original SQ8L.dll: LFO tables.\n")
        f.write("// Do not edit.\n#include <cstdint>\n\nnamespace sq8l::data {\n\n")
        f.write("\n\n".join(parts))
        f.write("\n\n}  // namespace sq8l::data\n")


if __name__ == "__main__":
    main()
