"""Extract the editor's bitmaps exactly as the ORIGINAL decoded them and generate
src/gui/data/*.cpp.

The original editor is opened headless in the emulator (oracle/gui_driver.Editor). We then
read, from emulator memory:

* the form background: Form.Brush.Bitmap, into which FormShow (plugEdit 0x483d9c) draws the
  ImgBack TJPEGImage (decoded by Delphi's jpeg unit inside the emulator);
* every TAniGIF strip (KnobGif, charGIF, numCharGIF, LedGIF, ButtGIF, smallButtGIF,
  upDownGif, scrButtGif): the frame TBitmaps that TAniGIF.Loaded (0x457200) decoded with
  the original's own CGIFDecoder.

Storage: palette (0x00RRGGBB) + indices. Every GIF strip has <= 256 colours (uint8 indices,
frame-major, row-major); the background has 1673 colours (uint16 indices).

Usage: python re/scripts/extract_gui_assets.py
"""
import os
import sys

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "tests"))
from test_gui_state import GIF_NAMES, OriginalGui  # noqa: E402

OUT = os.path.join(ROOT, "src", "gui", "data")


def c_array(name, data, ctype, per_line=24):
    lines = [f"extern const {ctype} {name}[{len(data)}];", f"alignas(16) const {ctype} {name}[{len(data)}] = {{"]
    for i in range(0, len(data), per_line):
        lines.append("    " + ",".join(str(int(v)) for v in data[i:i + per_line]) + ",")
    lines.append("};")
    return "\n".join(lines)


def hex_array(name, data, per_line=12):
    lines = [f"extern const uint32_t {name}[{len(data)}];", f"alignas(16) const uint32_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), per_line):
        lines.append("    " + ",".join("0x%06x" % int(v) for v in data[i:i + per_line]) + ",")
    lines.append("};")
    return "\n".join(lines)


def palettize(pixels):
    """pixels: N x 3 uint8 -> (palette as 0xRRGGBB list in first-use order, indices)."""
    packed = (pixels[:, 0].astype(np.uint32) << 16) | (pixels[:, 1].astype(np.uint32) << 8) | pixels[:, 2]
    uniq, first, inv = np.unique(packed, return_index=True, return_inverse=True)
    order = np.argsort(first)            # stable palette: order of first appearance
    rank = np.empty_like(order)
    rank[order] = np.arange(len(order))
    return uniq[order], rank[inv]


def write(fname, body, what):
    with open(os.path.join(OUT, fname), "w") as f:
        f.write(f"// Generated by re/scripts/extract_gui_assets.py from the original SQ8L.dll: {what}.\n")
        f.write("// Do not edit.\n#include \"GuiData.h\"\n\nnamespace sq8l::gui::data {\n\n")
        f.write(body)
        f.write("\n\n}  // namespace sq8l::gui::data\n")


def main():
    os.makedirs(OUT, exist_ok=True)
    og = OriginalGui()
    og.frame()

    bg = og.background_pixels()
    assert bg.shape == (430, 626, 3), bg.shape
    pal, idx = palettize(bg.reshape(-1, 3))
    assert len(pal) <= 65536
    write("GuiBackground.cpp",
          f"const int kBackgroundPaletteSize = {len(pal)};\n\n"
          + hex_array("kBackgroundPalette", pal) + "\n\n" + c_array("kBackgroundIndex", idx, "uint16_t", 32),
          "editor background (Form.Brush.Bitmap = ImgBack JPEG decoded by the original), 626x430")

    body = []
    table = []
    for name in GIF_NAMES:
        info = og.gif_info(name)
        frames = og.gif_frames(name)
        assert info["loaded"] and len(frames) == info["count"]
        for fr in frames:
            assert fr.shape == (info["h"], info["w"], 3)
        allpx = np.concatenate([fr.reshape(-1, 3) for fr in frames])
        pal, idx = palettize(allpx)
        assert len(pal) <= 256, (name, len(pal))
        body.append(hex_array(f"k{name}Palette", pal))
        body.append(c_array(f"k{name}Index", idx, "uint8_t", 40))
        table.append((name, info["w"], info["h"], info["count"], len(pal)))
        print(f"{name}: {info['count']} frames {info['w']}x{info['h']}, {len(pal)} colours")
    assert len(table) == 8
    body.append(f"const SpriteData kSprites[kSpriteCount] = {{")
    for (name, w, h, n, npal) in table:
        body.append(f'    {{"{name}", {w}, {h}, {n}, k{name}Palette, {npal}, k{name}Index}},')
    body.append("};")
    write("GuiSprites.cpp", "\n\n".join(body[:-len(table) - 1]) + "\n\n" + "\n".join(body[-len(table) - 1:]),
          "TAniGIF frame strips as decoded by the original's CGIFDecoder")
    print("background: %d colours" % len(np.unique(bg.reshape(-1, 3), axis=0)))


if __name__ == "__main__":
    main()
