"""Extract data blobs from the original (static tables from the DLL, runtime-decompressed
data from the emulator) and generate C++ sources in src/engine/data/."""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "oracle"))
sys.path.insert(0, os.path.join(ROOT, "tests"))
from harness import started_host, master_ptr  # noqa: E402

OUT = os.path.join(ROOT, "src", "engine", "data")


def c_array(name, data, ctype="uint8_t", per_line=24):
    lines = [f"extern const {ctype} {name}[{len(data)}];", f"alignas(16) const {ctype} {name}[{len(data)}] = {{"]
    for i in range(0, len(data), per_line):
        lines.append("    " + ",".join(str(b) for b in data[i:i + per_line]) + ",")
    lines.append("};")
    return "\n".join(lines)


def write(fname, body, what):
    with open(os.path.join(OUT, fname), "w") as f:
        f.write(f"// Generated by re/scripts/extract_data.py from the original SQ8L.dll: {what}.\n")
        f.write("// Do not edit.\n#include <cstdint>\n\nnamespace sq8l::data {\n\n")
        f.write(body)
        f.write("\n\n}  // namespace sq8l::data\n")


def main():
    h = started_host()
    e = h.emu
    doc = e.u32(master_ptr(h) + 0x1000)
    rom = e.read(e.u32(doc + 0x2008), 0x40000)
    write("WaveRomData.cpp", c_array("kWaveRom", rom),
          "SQ-80 wave ROM (256 KiB), as decompressed by the original at load (CpackDlt36)")
    keymap = e.read(0x494318, 75 * 16)
    records = e.read(0x4947C8, 4 * (max(keymap) + 1))
    write("WaveParamsData.cpp",
          c_array("kWaveKeyMap", keymap) + "\n\n" + c_array("kWaveSampleRecords", records),
          "wave -> key range -> wavesample record tables (0x494318, 0x4947c8)")
    print("rom", len(rom), "keymap", len(keymap), "records", len(records) // 4)


if __name__ == "__main__":
    main()
