"""Extract the factory sound banks as the original holds them after load and generate
src/engine/data/FactoryBanks.cpp.

At DLL load the CsoundLib object (unit soundLibrary) initialises all 512 slots with the INIT
program, then FUN_004552a4 fills
  * bank C (slots 256..383): CpackRle25-decompressed SQ8L library blob (0x489c54, 0x96cf bytes),
  * bank D (slots 384..423): the 40 SQ80 factory programs (raw 102-byte ESQ-1 format at 0x493324)
    converted by FUN_00454aec(src, dst, 1, 0, 4, -12); slots 424..511 keep the INIT program.
We read the 512-slot table straight from the emulated library object.
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "oracle"))
sys.path.insert(0, os.path.join(ROOT, "tests"))
from harness import started_host  # noqa: E402

OUT = os.path.join(ROOT, "src", "engine", "data", "FactoryBanks.cpp")

LIB_GLOBAL = 0x494314      # CsoundLib instance pointer
PROG_SIZE = 0x21C
SLOTS = 0x20               # first program slot inside CsoundLib
BANK_C, BANK_D, BANK_D_COUNT = 256, 384, 40


def c_rows(name, progs):
    lines = [f"extern const uint8_t {name}[{len(progs)}][{PROG_SIZE}];",
             f"const uint8_t {name}[{len(progs)}][{PROG_SIZE}] = {{"]
    for i, p in enumerate(progs):
        n = p[2]
        title = p[3:3 + min(n, 15)].decode("latin1").replace("\\", "/").replace("*/", "* /")
        lines.append(f"    // {i:3d} {title}")
        lines.append("    {")
        for j in range(0, len(p), 30):
            lines.append("        " + ",".join(str(b) for b in p[j:j + 30]) + ",")
        lines.append("    },")
    lines.append("};")
    return "\n".join(lines)


def main():
    h = started_host()
    e = h.emu
    lib = e.u32(LIB_GLOBAL)
    progs = [e.read(lib + SLOTS + i * PROG_SIZE, PROG_SIZE) for i in range(512)]
    bank_c = progs[BANK_C:BANK_C + 128]
    bank_d = progs[BANK_D:BANK_D + BANK_D_COUNT]
    with open(OUT, "w") as f:
        f.write("// Generated by re/scripts/extract_library_data.py from the original SQ8L.dll: factory\n"
                "// banks C (SQ8L factory, 128 programs) and D (SQ80 factory, 40 programs) exactly as the\n"
                "// original library holds them after load (540-byte program records).\n"
                "// Do not edit.\n#include <cstdint>\n\nnamespace sq8l::data {\n\n")
        f.write(c_rows("kFactoryBankC", bank_c))
        f.write("\n\n")
        f.write(c_rows("kFactoryBankD", bank_d))
        f.write("\n\n}  // namespace sq8l::data\n")
    print("bank C", len(bank_c), "bank D", len(bank_d), "->", OUT)


if __name__ == "__main__":
    main()
