"""Extract the static (non-derivable) tables used by the final amplifier (unit mod_amp4_13)
from the original SQ8L.dll and generate src/engine/data/AmpData.cpp.

* 0x4c2110: DCA4 level curve, 256 Singles (level 0..255 -> linear gain 0..2), reached by the
  amp through the pointer variable at 0x4c33c0 (never reassigned).
* 0x4c2510: unit satTables source records, 2 x 4 Singles
  {drive at SAT=0, drive at max SAT, gain with SAT off, gain at max SAT}; the unit init
  (FUN_0045e33c) expands them into 2 x 65 {drive, gain} pairs (computed in C++).

The tables computed at load time (pan law, saturation tables) are computed in C++ and checked
against emulator memory by tests/test_amp.py.
"""
import os
import struct

import pefile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DLL = os.path.join(ROOT, "original", "SQ8L.dll")
OUT = os.path.join(ROOT, "src", "engine", "data", "AmpData.cpp")

AMP_SHAPE = 0x4C2110
SAT_PARAMS = 0x4C2510


def f32_literal(x):
    """Exact C++ hex float literal of a Single."""
    if x == 0:
        return "0.0f"
    mant, exp = x.hex().split("p")
    mant = mant.rstrip("0").rstrip(".")
    return f"{mant}p{exp}f"


def float_array(name, values, dims, per_line=4):
    shape = "".join(f"[{d}]" for d in dims)
    lines = [f"extern const float {name}{shape};", f"alignas(16) const float {name}{shape} = {{"]
    if len(dims) == 2:  # one braced row per first index
        for i in range(0, len(values), dims[1]):
            lines.append("    {" + ", ".join(f32_literal(v) for v in values[i:i + dims[1]]) + "},")
    else:
        for i in range(0, len(values), per_line):
            lines.append("    " + ", ".join(f32_literal(v) for v in values[i:i + per_line]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    pe = pefile.PE(DLL, fast_load=True)
    base = pe.OPTIONAL_HEADER.ImageBase

    def singles(addr, n):
        return list(struct.unpack(f"<{n}f", pe.get_data(addr - base, 4 * n)))

    shape = singles(AMP_SHAPE, 256)
    sat = singles(SAT_PARAMS, 8)
    body = "\n\n".join([
        "// DCA4 level (0..255) -> linear gain (0x4c2110).\n" + float_array("kAmpShape", shape, [256]),
        "// Saturation table parameters per table: {drive at SAT=0, drive at max SAT,\n"
        "// gain with SAT off, gain at max SAT} (0x4c2510; only table 0 is used).\n"
        + float_array("kSatParams", sat, [2, 4]),
    ])
    with open(OUT, "w") as f:
        f.write("// Generated by re/scripts/extract_amp_data.py from the original SQ8L.dll:\n")
        f.write("// static tables of the final amplifier (units sqAmpShp/satTables). Do not edit.\n")
        f.write("namespace sq8l::data {\n\n")
        f.write(body)
        f.write("\n\n}  // namespace sq8l::data\n")
    print(f"wrote {OUT}: amp shape {len(shape)}, sat params {len(sat)}")


if __name__ == "__main__":
    main()
