"""Extract the static tables used by the envelope (mod_env_2) and mod follower / glide code
from the original SQ8L.dll and generate src/engine/data/EnvData.cpp.

All these tables are initialized data in the DATA section (they are NOT computed at load
time: tests/test_env.py checks that the emulator memory after load equals these bytes).
The tables are reached through pointer variables, which are resolved here too.
"""
import os
import struct

import pefile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DLL = os.path.join(ROOT, "original", "SQ8L.dll")
OUT = os.path.join(ROOT, "src", "engine", "data", "EnvData.cpp")

# pointer variable -> (symbol, C type, element count, element size, description)
TABLES = [
    (0x4C3158, "kEnvTimeTable", "uint16_t", 64, 2,
     "time (T1..T4, glide) -> duration in control ticks at 83.592575 Hz (0x4c2090)"),
    (0x4C3150, "kEnvShapeTables", "int8_t", 8 * 256, 1,
     "8 signed shaping curves of 256 entries: EXP, EXP2, EXP3, EXP4, TAN, TAN2, TAN3, TAN4 "
     "(0x4c1688; envelopes use 0..6, the LFO uses all 8 as waveforms 75..82)"),
    (0x4C321C, "kVelocityCurveLinear", "uint8_t", 128, 1,
     "velocity -> level scaling for LV 0..63 'L' (0x494d4c)"),
    (0x4C316C, "kVelocityCurveExp", "uint8_t", 128, 1,
     "velocity -> level scaling for LV 64..127 'X' (0x494dcc)"),
]


def main():
    pe = pefile.PE(DLL)
    base = pe.OPTIONAL_HEADER.ImageBase

    def read(addr, n):
        return pe.get_data(addr - base, n)

    lines = [
        "// Generated by re/scripts/extract_env_data.py from the original SQ8L.dll: static tables",
        "// of the envelope unit (mod_env_2) and of the glide code (plugCore). Do not edit.",
        "#include <cstdint>",
        "",
        "namespace sq8l::data {",
        "",
    ]
    for ptr_var, name, ctype, count, size, what in TABLES:
        addr = struct.unpack("<I", read(ptr_var, 4))[0]
        raw = read(addr, count * size)
        fmt = {("int8_t", 1): "b", ("uint8_t", 1): "B", ("uint16_t", 2): "H"}[(ctype, size)]
        values = struct.unpack(f"<{count}{fmt}", raw)
        lines.append(f"// {what}; pointer variable {ptr_var:#x} -> {addr:#x}")
        lines.append(f"extern const {ctype} {name}[{count}];")
        lines.append(f"alignas(16) const {ctype} {name}[{count}] = {{")
        per_line = 16
        for i in range(0, count, per_line):
            lines.append("    " + ", ".join(str(v) for v in values[i:i + per_line]) + ",")
        lines.append("};")
        lines.append("")
    lines.append("}  // namespace sq8l::data")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
