"""Extract the static data tables used by the master (unit plugCore) and generate
src/engine/data/MasterData.cpp.

Every table is read from the emulator after the plugin has been loaded and started,
and checked to be identical to the DLL file contents (i.e. not computed at load).
The mod-source table at 0x4c4848 (BSS, filled by the midiParser unit initialization
FUN_0044feec) is computed in C++ instead (Master.cpp, kModSources)."""
import os
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "oracle"))
sys.path.insert(0, os.path.join(ROOT, "tests"))
from harness import started_host  # noqa: E402

OUT = os.path.join(ROOT, "src", "engine", "data", "MasterData.cpp")

# (C name, pointer variable used by the code, element type, count, description)
TABLES = [
    ("kVelocityCurve1", 0x4C321C, "uint8_t", 128,
     "velocity -> voice mod source 8 (voice+0xb8), FUN_004625d4"),
    ("kVelocityCurve2", 0x4C316C, "uint8_t", 128,
     "velocity -> voice mod source 9 (voice+0xbc), FUN_004625d4"),
    ("kFadeInTime", 0x4C3248, "float", 4,
     "voice-steal fade-in time in seconds by min(program[0x9b], 3), FUN_004625d4"),
    ("kAmpRampTime", 0x4C33FC, "float", 8,
     "amp ramp time in seconds [dca4Mode][min(program[0x9b], 3)] (FUN_0045e7f8), FUN_004625d4 / FUN_00463890"),
    ("kAmpSmoothing", 0x4C32F0, "int32_t", 2,
     "amp smoothing by dca4Mode (FUN_0045e848 argument, all 0), FUN_00463890"),
    # Indexed by the signed program byte 0x173 (1..127); the SQ-80 range is 1..63, the
    # following entries are the (static) bytes that follow the table in the DLL.
    ("kGlideTime", 0x4C3158, "uint16_t", 128,
     "time table (also the envelope times) used as glide divisor by program[0x173], FUN_004625d4 / FUN_00462ca0"),
]

FMT = {"uint8_t": "B", "uint16_t": "H", "int32_t": "i", "float": "f"}


def fmt_value(ctype, v):
    if ctype == "float":
        return f"{float(v).hex()}f /*{v!r}*/"
    return str(v)


def main():
    h = started_host()
    e = h.emu
    pe = e.pe
    ib = pe.OPTIONAL_HEADER.ImageBase
    out = ["// Generated by re/scripts/extract_master_data.py from the original SQ8L.dll:",
           "// static tables used by the master (unit plugCore). Do not edit.",
           "#include <cstdint>", "", "namespace sq8l::data {", ""]
    for name, ptr, ctype, count, desc in TABLES:
        addr = e.u32(ptr)
        size = struct.calcsize(FMT[ctype]) * count
        mem = e.read(addr, size)
        filedata = pe.get_data(addr - ib, size)
        if mem != filedata:
            raise SystemExit(f"{name}: emulator memory differs from the DLL file (computed at load?)")
        values = struct.unpack(f"<{count}{FMT[ctype]}", mem)
        out.append(f"// {desc}; {ctype} at {addr:#x} (via pointer {ptr:#x})")
        out.append(f"extern const {ctype} {name}[{count}];")
        out.append(f"const {ctype} {name}[{count}] = {{")
        per = 4 if ctype == "float" else 16
        for i in range(0, count, per):
            out.append("    " + ", ".join(fmt_value(ctype, v) for v in values[i:i + per]) + ",")
        out.append("};")
        out.append("")
        print(f"{name}: {count} x {ctype} at {addr:#x}")
    out.append("}  // namespace sq8l::data")
    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
