"""Extract the static tables used by the DOC oscillator unit (mod_doc8_5 / docPitch) from the
original SQ8L.dll and generate src/engine/data/DocData.cpp.

Both tables are initialized data in the DLL's DATA section (not computed at load time); the
differential test (tests/test_doc.py) checks that the emulated plugin's memory still holds
the same values after start-up.
"""
import os
import struct

import pefile

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DLL = os.path.join(ROOT, "original", "SQ8L.dll")
OUT = os.path.join(ROOT, "src", "engine", "data", "DocData.cpp")

PITCH_TABLE = 0x4C0278   # uint16[2049]: DOC frequency register per 1/16 semitone (FUN_0045b8b4)
PITCH_COUNT = 2049       # index 0x800 is read when interpolating the last entry
LEVEL_TABLE = 0x4C127C   # float[256]: DCA level -> amplitude (pointer at 0x4c3124, FUN_0045c568)
LEVEL_COUNT = 256


def read(pe, addr, n):
    return pe.get_data(addr - pe.OPTIONAL_HEADER.ImageBase, n)


def float_lit(bits):
    """C++ hex float literal that reproduces the float bits exactly."""
    x = struct.unpack("<f", struct.pack("<I", bits))[0]
    if x == 0:
        return "0.0f" if bits == 0 else "-0.0f"
    return f"{x.hex()}f"


def main():
    pe = pefile.PE(DLL)
    pitch = struct.unpack(f"<{PITCH_COUNT}H", read(pe, PITCH_TABLE, 2 * PITCH_COUNT))
    level_bits = struct.unpack(f"<{LEVEL_COUNT}I", read(pe, LEVEL_TABLE, 4 * LEVEL_COUNT))

    lines = [
        "// Generated by re/scripts/extract_doc_data.py from the original SQ8L.dll: DOC pitch table",
        "// (0x4c0278) and DCA level table (0x4c127c).",
        "// Do not edit.",
        "#include <cstdint>",
        "",
        "namespace sq8l::data {",
        "",
        f"extern const uint16_t kDocPitchTable[{PITCH_COUNT}];",
        f"alignas(16) const uint16_t kDocPitchTable[{PITCH_COUNT}] = {{",
    ]
    for i in range(0, PITCH_COUNT, 16):
        lines.append("    " + ",".join(str(v) for v in pitch[i:i + 16]) + ",")
    lines += ["};", "", f"extern const float kDocLevelTable[{LEVEL_COUNT}];",
              f"alignas(16) const float kDocLevelTable[{LEVEL_COUNT}] = {{"]
    for i in range(0, LEVEL_COUNT, 4):
        lines.append("    " + ", ".join(float_lit(b) for b in level_bits[i:i + 4]) + ",")
    lines += ["};", "", "}  // namespace sq8l::data", ""]
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}: pitch {PITCH_COUNT} entries, level {LEVEL_COUNT} entries")


if __name__ == "__main__":
    main()
